### ISSUE TITLE
questions on training

### ISSUE THREAD

**Issue by dsplog** [yl4579/StyleTTS2#21] opened 2023-10-26 02:18 UTC
a) when loading check point for train_second.py, apart from the nets for mpd, msd and wd, saw the need to add the prefix "module." to make the key names compatible. is this expected ? 

```
diff --git a/models.py b/models.py
index 99b4f3d..fc03a8b 100644
--- a/models.py
+++ b/models.py

+from collections import OrderedDict
 
 class LearnedDownSample(nn.Module):
     def __init__(self, layer_type, dim_in):
@@ -697,9 +700,19 @@ def load_checkpoint(model, optimizer, path, load_only_params=True, ignore_module
     state = torch.load(path, map_location='cpu')
     params = state['net']
     for key in model:
+        new_state_dict = OrderedDict()
+        for k, v in params[key].items():
+            name = 'module.' + k # add `module.`
+            new_state_dict[name] = v
+
+        if key in ['mpd', 'msd', 'wd'] : 
+            new_state_dict = params[key]    
+
         if key in params and key not in ignore_modules:
             print('%s loaded' % key)
-            model[key].load_state_dict(params[key])
+            #model[key].load_state_dict(params[key])
+            model[key].load_state_dict(new_state_dict)
+
     _ = [model[key].eval() for key in model]
```
     

b) passing pre-trained model for train_second.py 
after training first stage for around 50 epochs, defined the params`first_stage_path` and `pre-trained_model`
anything more needed ? 

```
diff --git a/Configs/config.yml b/Configs/config.yml
index b74b8ee..2a9f93c 100644
--- a/Configs/config.yml
+++ b/Configs/config.yml
@@ -1,13 +1,13 @@
 log_dir: "Models/LJSpeech"
-first_stage_path: "first_stage.pth"
+first_stage_path: "epoch_1st_00048.pth"
 save_freq: 2
-batch_size: 16
-max_len: 400 # maximum number of frames
-pretrained_model: ""
+batch_size: 2
+max_len: 100 # maximum number of frames
+pretrained_model: "Models/LJSpeech/epoch_1st_00048.pth"
 second_stage_load_pretrained: true # set to true if the pre-trained model is for 2nd stage
 load_only_params: false # set to true if do not want to load epoch numbers and optimizer parameters
```
 
c) resume training in first stage? 
defining the params `first_stage_path` suffice ?
further, doing the modifications as done in a) does not seem to be needed.

**Comment by yl4579** [comment] 2023-10-27 20:28
a) Where did you get these code? They seem like old versions of this repo, so I’m not sure if you still need this in the current version.
b) I don’t think I understand your question, do you want to train the second stage from scratch or just resume training?
c) No, you need to specify the pretrained mode path to resume training.

**Comment by dsplog** [comment] 2023-10-27 20:36
a) got the code from [here](https://github.com/yl4579/StyleTTS2/blob/3e300817a2433e2c3832703e7973183cbf98effe/models.py#L696 ) `def load_checkpoint`

b) am training from scratch. to do that, was doing first stage training for ~100 epochs, and then starting second stage with giving the params `first_stage_path` and `pre-trained_model` in Config.yml

c) ok

**Comment by yl4579** [comment] 2023-10-28 05:12
a) In the current version, there is no `module.` prefix. Where did the code come from? 
`python
+        new_state_dict = OrderedDict()
+        for k, v in params[key].items():
+            name = 'module.' + k # add `module.`
+            new_state_dict[name] = v
+
+        if key in ['mpd', 'msd', 'wd'] : 
+            new_state_dict = params[key]    
+
         if key in params and key not in ignore_modules:
             print('%s loaded' % key)
-            model[key].load_state_dict(params[key])
+            #model[key].load_state_dict(params[key])
+            model[key].load_state_dict(new_state_dict)
+
`

b) If you are training from scratch, after you finish the first stage, you can directly proceed to the second stage without changing anything, as the first model will directly be saved at `first_stage_path` and the second stage script will load `first_stage_path`. The pre-trained model path is only useful if you want to resume training.

**Comment by dsplog** [comment] 2023-10-29 00:56
a) ah, the module. prefix was added by me to work around :-) 
was facing issues similar to what is described in https://stackoverflow.com/a/61910320 

b) ok, thanks for the note

**Comment by yl4579** [comment] 2023-10-29 04:00
Not sure why you would need this work around. Did you get any errors without this?

**Comment by ruby11dog** [comment] 2023-10-30 02:58
it happens to me either, the problem is when I start to train in stage 2, the model can't read the stage 1 model properly, the problem is the expect key and actual key are not corresponding: Missing key(s) in state_dict. e.g: "**module**.decode.0.conv1.bias", "**module**.decode.0.conv1.weight_g"] Unexpected key(s) in state_dict: "decode.0.conv1.bias", "decode.0.conv1.weight_g"]

**Comment by yl4579** [comment] 2023-10-30 06:21
@ruby11dog I have yet to encounter this problem myself. How to reproduce this error?

**Comment by dsplog** [comment] 2023-10-31 01:35
@yl4579  : 
as mentioned in this [post](https://github.com/pytorch/pytorch/issues/9176), the issue is caused when model is saved in _"when model is trained using DataParallel(), the saved model state_dict will have prefix "module." before the names of all layers."_

this issue is not seen if DataParallel() is used before loading the model. 

another thread which discuss this topic [here](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/7)

**Comment by yl4579** [comment] 2023-10-31 01:52
I think DataParallel is used before loading in [train_second.py](https://github.com/yl4579/StyleTTS2/blob/main/train_second.py#L134) isn't?

**Comment by ruby11dog** [comment] 2023-10-31 01:55
> @ruby11dog I have yet to encounter this problem myself. How to reproduce this error?

as @dsplog says, it happens when training the first stage model using DP. BTW, I'm looking for the multi-speaker version, do you have any plan to support multi-speaker training?

**Comment by yl4579** [comment] 2023-10-31 02:10
The first stage is DDP, not DP. Did you change the code or something?

Multispeaker training is already supported, you just need to change the multispeaker flag to true. There’s no inference demo because I’m still working on the LibriTTS model training, but I’m running the exactly same code as in the repo now.

**Comment by ruby11dog** [comment] 2023-10-31 06:43
> The first stage is DDP, not DP. Did you change the code or something?
> 
> Multispeaker training is already supported, you just need to change the multispeaker flag to true. There’s no inference demo because I’m still working on the LibriTTS model training, but I’m running the exactly same code as in the repo now.

I did not use "accelarete launch" method in training the first stage because of its instability, T taining process will be interrupted by errors sometimes. Maybe that's the reason the checkpoint name problem happens to me.

Thanks for the multispeaker work! I'll try it in a minute. 

Another question, is there any plan to publish a chinese plbert model in the future?

Thanks for your excellent work again!

**Comment by liuhuang31** [comment] 2023-10-31 11:11
(1) if not use "accelarete launch", when train second stage, the problem is same as
[load_checkpoint_error](https://github.com/yl4579/StyleTTS2/issues/21#issuecomment-1784398791)

(2) if use "accelarete launch", but only use one gpu, it also appear load_checkpoint_error in the second stage.

**Comment by yl4579** [comment] 2023-10-31 19:41
I think that's expected. The code was for accelerator only with multi-GPUs, so if you don't launch with accelerator of course you will get these errors.

**Closed by yl4579** 2023-10-31 19:41 UTC
